import { Component } from '@angular/core';

@Component({
  selector: 'ngs-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  set1 = [
    {key: 0, value: 'A'},
    {key: 1, value: 'B'},
    {key: 3, value: 'C'},
    {key: 4, value: 'D'},
    {key: 5, value: 'E'},
    {key: 6, value: 'F'},
    {key: 7, value: 'G'},
    {key: 8, value: 'H'},
    {key: 9, value: 'I'},
    {key: 10, value: 'J'},
    {key: 11, value: 'K'},
    {key: 12, value: 'L'},
    {key: 13, value: 'M'},
    {key: 14, value: 'N'},
    {key: 15, value: 'O'},
    {key: 16, value: 'P'},
    {key: 17, value: 'P'},
    {key: 18, value: 'Q'},
    {key: 19, value: 'R'},
    {key: 20, value: 'S'},
    {key: 21, value: 'T'},
    {key: 22, value: 'U'},
    {key: 24, value: 'W'},
    {key: 25, value: 'X'},
    {key: 26, value: 'Y'},
    {key: 27, value: 'Z'},
  ]
    set = [{key: 0, value:'4a'},
    {key: 1, value:'4a+'},
    {key: 2, value:'4b'},
    {key: 3, value:'4b+'},
    {key: 4, value:'4c'},
    {key: 5, value:'4c+'},
    {key: 6, value:'5a'},
    {key: 7, value:'5a+'},
    {key: 8, value:'5b'},
    {key: 9, value:'5b+'},
    {key: 10, value:'5c'},
    {key: 11, value:'5c+'},
    {key: 12, value:'6a'},
    {key: 13, value:'6a+'},
    {key: 14, value:'6b'},
    {key: 15, value:'6b+'},
    {key: 16, value:'6c'},
    {key: 17, value:'6c+'},
    {key: 18, value:'7a'},
    {key: 19, value:'7a+'},
    {key: 20, value:'7b'},
    {key: 21, value:'7b+'},
    {key: 22, value:'7c'},
    {key: 23, value:'7c+'},
    {key: 24, value:'8a'},
    {key: 25, value:'8a+'},
    {key: 26, value:'8b'},
    {key: 27, value:'8b+'},
    {key: 28, value:'8c'},
    {key: 29, value:'8c+'},
    {key: 30, value:'9a'},]
  
}
